name: Terraform Format Check

on:
  push:
    branches:
      - main

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Terraform Format
        run: terraform fmt -check -recursive
