name: Terraform Format Check

on:
  push:
    branches:
      - main

jobs:
  terraform-fmt:
    name: Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Format Check
        run: terraform fmt -check -recursive
